language: go
go:
  - 1.7.3
  - tip

os:
  - linux
  - osx

sudo: false

install:
  - echo "skipping travis' default go get -t -v to ensure we're only using vendor/ dependencies"

script:
  - make test
